"""empty message

Revision ID: 80bb22f1e9f9
Revises: aa4f7a08dc50
Create Date: 2020-06-19 01:57:58.944074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80bb22f1e9f9'
down_revision = 'aa4f7a08dc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('duration', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
