"""empty message

Revision ID: c872f001c008
Revises: 
Create Date: 2020-06-18 19:15:36.224184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c872f001c008'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Time(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('icon_path', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('album', 'compilation', 'concert', name='album_type'), server_default=sa.text("'album'::album_type"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_type'), 'album', ['type'], unique=False)
    op.create_table('artist',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('icon_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('group',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('icon_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon_path', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_table('history_artist_table',
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('end_date', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist'], ['artist.name'], ),
    sa.ForeignKeyConstraint(['group'], ['group.name'], ),
    sa.PrimaryKeyConstraint('artist', 'group')
    )
    op.create_index(op.f('ix_history_artist_table_artist'), 'history_artist_table', ['artist'], unique=False)
    op.create_index(op.f('ix_history_artist_table_group'), 'history_artist_table', ['group'], unique=False)
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('album', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_year'), 'song', ['year'], unique=False)
    op.create_table('artists_table',
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('song', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['group.name'], ),
    sa.ForeignKeyConstraint(['song'], ['song.id'], )
    )
    op.create_table('groups_table',
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('song', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['group.name'], ),
    sa.ForeignKeyConstraint(['song'], ['song.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups_table')
    op.drop_table('artists_table')
    op.drop_index(op.f('ix_song_year'), table_name='song')
    op.drop_table('song')
    op.drop_index(op.f('ix_history_artist_table_group'), table_name='history_artist_table')
    op.drop_index(op.f('ix_history_artist_table_artist'), table_name='history_artist_table')
    op.drop_table('history_artist_table')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('artist')
    op.drop_index(op.f('ix_album_type'), table_name='album')
    op.drop_table('album')
    # ### end Alembic commands ###
